package com.simon.boot.word.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WordDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public WordDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTmIdIsNull() {
            addCriterion("tm_id is null");
            return (Criteria) this;
        }

        public Criteria andTmIdIsNotNull() {
            addCriterion("tm_id is not null");
            return (Criteria) this;
        }

        public Criteria andTmIdEqualTo(Long value) {
            addCriterion("tm_id =", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdNotEqualTo(Long value) {
            addCriterion("tm_id <>", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdGreaterThan(Long value) {
            addCriterion("tm_id >", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tm_id >=", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdLessThan(Long value) {
            addCriterion("tm_id <", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdLessThanOrEqualTo(Long value) {
            addCriterion("tm_id <=", value, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdIn(List<Long> values) {
            addCriterion("tm_id in", values, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdNotIn(List<Long> values) {
            addCriterion("tm_id not in", values, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdBetween(Long value1, Long value2) {
            addCriterion("tm_id between", value1, value2, "tmId");
            return (Criteria) this;
        }

        public Criteria andTmIdNotBetween(Long value1, Long value2) {
            addCriterion("tm_id not between", value1, value2, "tmId");
            return (Criteria) this;
        }

        public Criteria andWordChIsNull() {
            addCriterion("word_ch is null");
            return (Criteria) this;
        }

        public Criteria andWordChIsNotNull() {
            addCriterion("word_ch is not null");
            return (Criteria) this;
        }

        public Criteria andWordChEqualTo(String value) {
            addCriterion("word_ch =", value, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChNotEqualTo(String value) {
            addCriterion("word_ch <>", value, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChGreaterThan(String value) {
            addCriterion("word_ch >", value, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChGreaterThanOrEqualTo(String value) {
            addCriterion("word_ch >=", value, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChLessThan(String value) {
            addCriterion("word_ch <", value, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChLessThanOrEqualTo(String value) {
            addCriterion("word_ch <=", value, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChLike(String value) {
            addCriterion("word_ch like", value, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChNotLike(String value) {
            addCriterion("word_ch not like", value, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChIn(List<String> values) {
            addCriterion("word_ch in", values, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChNotIn(List<String> values) {
            addCriterion("word_ch not in", values, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChBetween(String value1, String value2) {
            addCriterion("word_ch between", value1, value2, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordChNotBetween(String value1, String value2) {
            addCriterion("word_ch not between", value1, value2, "wordCh");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolIsNull() {
            addCriterion("word_phonetic_symbol is null");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolIsNotNull() {
            addCriterion("word_phonetic_symbol is not null");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolEqualTo(String value) {
            addCriterion("word_phonetic_symbol =", value, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolNotEqualTo(String value) {
            addCriterion("word_phonetic_symbol <>", value, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolGreaterThan(String value) {
            addCriterion("word_phonetic_symbol >", value, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("word_phonetic_symbol >=", value, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolLessThan(String value) {
            addCriterion("word_phonetic_symbol <", value, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolLessThanOrEqualTo(String value) {
            addCriterion("word_phonetic_symbol <=", value, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolLike(String value) {
            addCriterion("word_phonetic_symbol like", value, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolNotLike(String value) {
            addCriterion("word_phonetic_symbol not like", value, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolIn(List<String> values) {
            addCriterion("word_phonetic_symbol in", values, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolNotIn(List<String> values) {
            addCriterion("word_phonetic_symbol not in", values, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolBetween(String value1, String value2) {
            addCriterion("word_phonetic_symbol between", value1, value2, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordPhoneticSymbolNotBetween(String value1, String value2) {
            addCriterion("word_phonetic_symbol not between", value1, value2, "wordPhoneticSymbol");
            return (Criteria) this;
        }

        public Criteria andWordEnIsNull() {
            addCriterion("word_en is null");
            return (Criteria) this;
        }

        public Criteria andWordEnIsNotNull() {
            addCriterion("word_en is not null");
            return (Criteria) this;
        }

        public Criteria andWordEnEqualTo(String value) {
            addCriterion("word_en =", value, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnNotEqualTo(String value) {
            addCriterion("word_en <>", value, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnGreaterThan(String value) {
            addCriterion("word_en >", value, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnGreaterThanOrEqualTo(String value) {
            addCriterion("word_en >=", value, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnLessThan(String value) {
            addCriterion("word_en <", value, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnLessThanOrEqualTo(String value) {
            addCriterion("word_en <=", value, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnLike(String value) {
            addCriterion("word_en like", value, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnNotLike(String value) {
            addCriterion("word_en not like", value, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnIn(List<String> values) {
            addCriterion("word_en in", values, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnNotIn(List<String> values) {
            addCriterion("word_en not in", values, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnBetween(String value1, String value2) {
            addCriterion("word_en between", value1, value2, "wordEn");
            return (Criteria) this;
        }

        public Criteria andWordEnNotBetween(String value1, String value2) {
            addCriterion("word_en not between", value1, value2, "wordEn");
            return (Criteria) this;
        }

        public Criteria andEStatusIsNull() {
            addCriterion("e_status is null");
            return (Criteria) this;
        }

        public Criteria andEStatusIsNotNull() {
            addCriterion("e_status is not null");
            return (Criteria) this;
        }

        public Criteria andEStatusEqualTo(Integer value) {
            addCriterion("e_status =", value, "eStatus");
            return (Criteria) this;
        }

        public Criteria andEStatusNotEqualTo(Integer value) {
            addCriterion("e_status <>", value, "eStatus");
            return (Criteria) this;
        }

        public Criteria andEStatusGreaterThan(Integer value) {
            addCriterion("e_status >", value, "eStatus");
            return (Criteria) this;
        }

        public Criteria andEStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_status >=", value, "eStatus");
            return (Criteria) this;
        }

        public Criteria andEStatusLessThan(Integer value) {
            addCriterion("e_status <", value, "eStatus");
            return (Criteria) this;
        }

        public Criteria andEStatusLessThanOrEqualTo(Integer value) {
            addCriterion("e_status <=", value, "eStatus");
            return (Criteria) this;
        }

        public Criteria andEStatusIn(List<Integer> values) {
            addCriterion("e_status in", values, "eStatus");
            return (Criteria) this;
        }

        public Criteria andEStatusNotIn(List<Integer> values) {
            addCriterion("e_status not in", values, "eStatus");
            return (Criteria) this;
        }

        public Criteria andEStatusBetween(Integer value1, Integer value2) {
            addCriterion("e_status between", value1, value2, "eStatus");
            return (Criteria) this;
        }

        public Criteria andEStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("e_status not between", value1, value2, "eStatus");
            return (Criteria) this;
        }

        public Criteria andChapterIdIsNull() {
            addCriterion("chapter_id is null");
            return (Criteria) this;
        }

        public Criteria andChapterIdIsNotNull() {
            addCriterion("chapter_id is not null");
            return (Criteria) this;
        }

        public Criteria andChapterIdEqualTo(Long value) {
            addCriterion("chapter_id =", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdNotEqualTo(Long value) {
            addCriterion("chapter_id <>", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdGreaterThan(Long value) {
            addCriterion("chapter_id >", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdGreaterThanOrEqualTo(Long value) {
            addCriterion("chapter_id >=", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdLessThan(Long value) {
            addCriterion("chapter_id <", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdLessThanOrEqualTo(Long value) {
            addCriterion("chapter_id <=", value, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdIn(List<Long> values) {
            addCriterion("chapter_id in", values, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdNotIn(List<Long> values) {
            addCriterion("chapter_id not in", values, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdBetween(Long value1, Long value2) {
            addCriterion("chapter_id between", value1, value2, "chapterId");
            return (Criteria) this;
        }

        public Criteria andChapterIdNotBetween(Long value1, Long value2) {
            addCriterion("chapter_id not between", value1, value2, "chapterId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_detail
     *
     * @mbg.generated do_not_delete_during_merge Wed May 15 10:50:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table word_detail
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}