package com.simon.boot.word.vo;

/**
 * @author simon.wei
 */
public class EmailVO {

    /**
     * 邮件ID
     */
    private Long id;

    /**
     * 收件人ids字符串
     */
    private String recipientIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.mail_title
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private String mailTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.mail_content
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private String mailContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.mail_title
     *
     * @return the value of oa_email.mail_title
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public String getMailTitle() {
        return mailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.mail_title
     *
     * @param mailTitle the value for oa_email.mail_title
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setMailTitle(String mailTitle) {
        this.mailTitle = mailTitle == null ? null : mailTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.mail_content
     *
     * @return the value of oa_email.mail_content
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public String getMailContent() {
        return mailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.mail_content
     *
     * @param mailContent the value for oa_email.mail_content
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setMailContent(String mailContent) {
        this.mailContent = mailContent == null ? null : mailContent.trim();
    }

    public String getRecipientIds() {
        return recipientIds;
    }

    public void setRecipientIds(String recipientIds) {
        this.recipientIds = recipientIds == null ? null : recipientIds.trim();
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
