package com.simon.boot.word.dao;

import com.simon.boot.word.pojo.OaEmail;
import com.simon.boot.word.pojo.OaEmailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface OaEmailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    long countByExample(OaEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    int deleteByExample(OaEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    int insert(OaEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    int insertSelective(OaEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    List<OaEmail> selectByExampleWithBLOBs(OaEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    List<OaEmail> selectByExample(OaEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    OaEmail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") OaEmail record, @Param("example") OaEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") OaEmail record, @Param("example") OaEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    int updateByExample(@Param("record") OaEmail record, @Param("example") OaEmailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    int updateByPrimaryKeySelective(OaEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(OaEmail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oa_email
     *
     * @mbg.generated Thu Jun 06 16:49:47 CST 2019
     */
    int updateByPrimaryKey(OaEmail record);
}