package com.simon.boot.word.dao;

import com.simon.boot.word.pojo.UserStudyLog;
import com.simon.boot.word.pojo.UserStudyLogExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface UserStudyLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    long countByExample(UserStudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    int deleteByExample(UserStudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    int insert(UserStudyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    int insertSelective(UserStudyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    List<UserStudyLog> selectByExample(UserStudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    UserStudyLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserStudyLog record, @Param("example") UserStudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    int updateByExample(@Param("record") UserStudyLog record, @Param("example") UserStudyLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    int updateByPrimaryKeySelective(UserStudyLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_study_log
     *
     * @mbg.generated Wed May 22 15:46:25 CST 2019
     */
    int updateByPrimaryKey(UserStudyLog record);
}