package com.simon.boot.word.dao;

import com.simon.boot.word.pojo.WordRole;
import com.simon.boot.word.pojo.WordRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface WordRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    long countByExample(WordRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    int deleteByExample(WordRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    int insert(WordRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    int insertSelective(WordRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    List<WordRole> selectByExample(WordRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    WordRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") WordRole record, @Param("example") WordRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    int updateByExample(@Param("record") WordRole record, @Param("example") WordRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    int updateByPrimaryKeySelective(WordRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_role
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    int updateByPrimaryKey(WordRole record);
}