package com.simon.boot.word.dao;

import com.simon.boot.word.pojo.WordUserStudy;
import com.simon.boot.word.pojo.WordUserStudyExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface WordUserStudyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    long countByExample(WordUserStudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    int deleteByExample(WordUserStudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    int insert(WordUserStudy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    int insertSelective(WordUserStudy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    List<WordUserStudy> selectByExample(WordUserStudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    WordUserStudy selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") WordUserStudy record, @Param("example") WordUserStudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    int updateByExample(@Param("record") WordUserStudy record, @Param("example") WordUserStudyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    int updateByPrimaryKeySelective(WordUserStudy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user_study
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    int updateByPrimaryKey(WordUserStudy record);
}