package com.simon.boot.word.dao;

import com.simon.boot.word.pojo.WordUser;
import com.simon.boot.word.pojo.WordUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface WordUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    long countByExample(WordUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    int deleteByExample(WordUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    int insert(WordUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    int insertSelective(WordUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    List<WordUser> selectByExample(WordUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    WordUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") WordUser record, @Param("example") WordUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    int updateByExample(@Param("record") WordUser record, @Param("example") WordUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    int updateByPrimaryKeySelective(WordUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table word_user
     *
     * @mbg.generated Mon May 20 11:31:50 CST 2019
     */
    int updateByPrimaryKey(WordUser record);
}