package com.simon.boot.word.pojo;

import java.util.Date;

public class OaEmail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.id
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.recipient_id
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private Long recipientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.sender_id
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private Long senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.oa_status
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private Integer oaStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.mail_title
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private String mailTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.create_time
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.update_time
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.is_check
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private Integer isCheck;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.sender_name
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private String senderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_email.mail_content
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    private String mailContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.id
     *
     * @return the value of oa_email.id
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.id
     *
     * @param id the value for oa_email.id
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.recipient_id
     *
     * @return the value of oa_email.recipient_id
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public Long getRecipientId() {
        return recipientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.recipient_id
     *
     * @param recipientId the value for oa_email.recipient_id
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setRecipientId(Long recipientId) {
        this.recipientId = recipientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.sender_id
     *
     * @return the value of oa_email.sender_id
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public Long getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.sender_id
     *
     * @param senderId the value for oa_email.sender_id
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setSenderId(Long senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.oa_status
     *
     * @return the value of oa_email.oa_status
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public Integer getOaStatus() {
        return oaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.oa_status
     *
     * @param oaStatus the value for oa_email.oa_status
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setOaStatus(Integer oaStatus) {
        this.oaStatus = oaStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.mail_title
     *
     * @return the value of oa_email.mail_title
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public String getMailTitle() {
        return mailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.mail_title
     *
     * @param mailTitle the value for oa_email.mail_title
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setMailTitle(String mailTitle) {
        this.mailTitle = mailTitle == null ? null : mailTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.create_time
     *
     * @return the value of oa_email.create_time
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.create_time
     *
     * @param createTime the value for oa_email.create_time
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.update_time
     *
     * @return the value of oa_email.update_time
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.update_time
     *
     * @param updateTime the value for oa_email.update_time
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.is_check
     *
     * @return the value of oa_email.is_check
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public Integer getIsCheck() {
        return isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.is_check
     *
     * @param isCheck the value for oa_email.is_check
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setIsCheck(Integer isCheck) {
        this.isCheck = isCheck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.sender_name
     *
     * @return the value of oa_email.sender_name
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public String getSenderName() {
        return senderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.sender_name
     *
     * @param senderName the value for oa_email.sender_name
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setSenderName(String senderName) {
        this.senderName = senderName == null ? null : senderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_email.mail_content
     *
     * @return the value of oa_email.mail_content
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public String getMailContent() {
        return mailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_email.mail_content
     *
     * @param mailContent the value for oa_email.mail_content
     *
     * @mbg.generated Thu Jun 06 11:22:29 CST 2019
     */
    public void setMailContent(String mailContent) {
        this.mailContent = mailContent == null ? null : mailContent.trim();
    }
}