package com.simon.boot.word.pojo;

import java.util.Date;

public class WordChapter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_chapter.id
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_chapter.chapter_name
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_chapter.create_time
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_chapter.update_time
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_chapter.ew_status
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    private Integer ewStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_chapter.tm_id
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    private Long tmId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_chapter.id
     *
     * @return the value of word_chapter.id
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_chapter.id
     *
     * @param id the value for word_chapter.id
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_chapter.chapter_name
     *
     * @return the value of word_chapter.chapter_name
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_chapter.chapter_name
     *
     * @param chapterName the value for word_chapter.chapter_name
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_chapter.create_time
     *
     * @return the value of word_chapter.create_time
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_chapter.create_time
     *
     * @param createTime the value for word_chapter.create_time
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_chapter.update_time
     *
     * @return the value of word_chapter.update_time
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_chapter.update_time
     *
     * @param updateTime the value for word_chapter.update_time
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_chapter.ew_status
     *
     * @return the value of word_chapter.ew_status
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public Integer getEwStatus() {
        return ewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_chapter.ew_status
     *
     * @param ewStatus the value for word_chapter.ew_status
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public void setEwStatus(Integer ewStatus) {
        this.ewStatus = ewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_chapter.tm_id
     *
     * @return the value of word_chapter.tm_id
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public Long getTmId() {
        return tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_chapter.tm_id
     *
     * @param tmId the value for word_chapter.tm_id
     *
     * @mbg.generated Mon May 20 11:38:14 CST 2019
     */
    public void setTmId(Long tmId) {
        this.tmId = tmId;
    }
}