package com.simon.boot.word.pojo;

import java.util.Date;

public class WordUserStudy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.user_id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.ew_status
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private Integer ewStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.tm_id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private Long tmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.tm_name
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private String tmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.chapter_id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private Long chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.chapter_name
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private String chapterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.create_time
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.update_time
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.correctness
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private String correctness;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.right_num
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private Integer rightNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_user_study.total_num
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    private Integer totalNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.id
     *
     * @return the value of word_user_study.id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.id
     *
     * @param id the value for word_user_study.id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.user_id
     *
     * @return the value of word_user_study.user_id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.user_id
     *
     * @param userId the value for word_user_study.user_id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.ew_status
     *
     * @return the value of word_user_study.ew_status
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public Integer getEwStatus() {
        return ewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.ew_status
     *
     * @param ewStatus the value for word_user_study.ew_status
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setEwStatus(Integer ewStatus) {
        this.ewStatus = ewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.tm_id
     *
     * @return the value of word_user_study.tm_id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public Long getTmId() {
        return tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.tm_id
     *
     * @param tmId the value for word_user_study.tm_id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setTmId(Long tmId) {
        this.tmId = tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.tm_name
     *
     * @return the value of word_user_study.tm_name
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public String getTmName() {
        return tmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.tm_name
     *
     * @param tmName the value for word_user_study.tm_name
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setTmName(String tmName) {
        this.tmName = tmName == null ? null : tmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.chapter_id
     *
     * @return the value of word_user_study.chapter_id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public Long getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.chapter_id
     *
     * @param chapterId the value for word_user_study.chapter_id
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setChapterId(Long chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.chapter_name
     *
     * @return the value of word_user_study.chapter_name
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.chapter_name
     *
     * @param chapterName the value for word_user_study.chapter_name
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName == null ? null : chapterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.create_time
     *
     * @return the value of word_user_study.create_time
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.create_time
     *
     * @param createTime the value for word_user_study.create_time
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.update_time
     *
     * @return the value of word_user_study.update_time
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.update_time
     *
     * @param updateTime the value for word_user_study.update_time
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.correctness
     *
     * @return the value of word_user_study.correctness
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public String getCorrectness() {
        return correctness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.correctness
     *
     * @param correctness the value for word_user_study.correctness
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setCorrectness(String correctness) {
        this.correctness = correctness == null ? null : correctness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.right_num
     *
     * @return the value of word_user_study.right_num
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public Integer getRightNum() {
        return rightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.right_num
     *
     * @param rightNum the value for word_user_study.right_num
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setRightNum(Integer rightNum) {
        this.rightNum = rightNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_user_study.total_num
     *
     * @return the value of word_user_study.total_num
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_user_study.total_num
     *
     * @param totalNum the value for word_user_study.total_num
     *
     * @mbg.generated Sat Jun 22 21:51:10 CST 2019
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }
}