package com.simon.boot.word.pojo;

import java.util.Date;

public class WordRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_role.id
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_role.role_name
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_role.create_time
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_role.update_time
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_role.ew_status
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    private Integer ewStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_role.id
     *
     * @return the value of word_role.id
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_role.id
     *
     * @param id the value for word_role.id
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_role.role_name
     *
     * @return the value of word_role.role_name
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_role.role_name
     *
     * @param roleName the value for word_role.role_name
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_role.create_time
     *
     * @return the value of word_role.create_time
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_role.create_time
     *
     * @param createTime the value for word_role.create_time
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_role.update_time
     *
     * @return the value of word_role.update_time
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_role.update_time
     *
     * @param updateTime the value for word_role.update_time
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_role.ew_status
     *
     * @return the value of word_role.ew_status
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    public Integer getEwStatus() {
        return ewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_role.ew_status
     *
     * @param ewStatus the value for word_role.ew_status
     *
     * @mbg.generated Tue Jun 18 16:04:16 CST 2019
     */
    public void setEwStatus(Integer ewStatus) {
        this.ewStatus = ewStatus;
    }
}