package com.simon.boot.word.pojo;

import java.util.Date;

public class WordSchool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_school.id
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_school.school_name
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    private String schoolName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_school.create_time
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_school.update_time
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_school.e_status
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    private Integer eStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_school.id
     *
     * @return the value of word_school.id
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_school.id
     *
     * @param id the value for word_school.id
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_school.school_name
     *
     * @return the value of word_school.school_name
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_school.school_name
     *
     * @param schoolName the value for word_school.school_name
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName == null ? null : schoolName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_school.create_time
     *
     * @return the value of word_school.create_time
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_school.create_time
     *
     * @param createTime the value for word_school.create_time
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_school.update_time
     *
     * @return the value of word_school.update_time
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_school.update_time
     *
     * @param updateTime the value for word_school.update_time
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_school.e_status
     *
     * @return the value of word_school.e_status
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    public Integer geteStatus() {
        return eStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_school.e_status
     *
     * @param eStatus the value for word_school.e_status
     *
     * @mbg.generated Tue May 14 17:21:39 CST 2019
     */
    public void seteStatus(Integer eStatus) {
        this.eStatus = eStatus;
    }
}