package com.simon.boot.word.pojo;

import java.util.Date;

public class WordDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_detail.id
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_detail.tm_id
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    private Long tmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_detail.word_ch
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    private String wordCh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_detail.word_phonetic_symbol
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    private String wordPhoneticSymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_detail.word_en
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    private String wordEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_detail.e_status
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    private Integer eStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_detail.chapter_id
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    private Long chapterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_detail.create_time
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column word_detail.update_time
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_detail.id
     *
     * @return the value of word_detail.id
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_detail.id
     *
     * @param id the value for word_detail.id
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_detail.tm_id
     *
     * @return the value of word_detail.tm_id
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public Long getTmId() {
        return tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_detail.tm_id
     *
     * @param tmId the value for word_detail.tm_id
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void setTmId(Long tmId) {
        this.tmId = tmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_detail.word_ch
     *
     * @return the value of word_detail.word_ch
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public String getWordCh() {
        return wordCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_detail.word_ch
     *
     * @param wordCh the value for word_detail.word_ch
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void setWordCh(String wordCh) {
        this.wordCh = wordCh == null ? null : wordCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_detail.word_phonetic_symbol
     *
     * @return the value of word_detail.word_phonetic_symbol
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public String getWordPhoneticSymbol() {
        return wordPhoneticSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_detail.word_phonetic_symbol
     *
     * @param wordPhoneticSymbol the value for word_detail.word_phonetic_symbol
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void setWordPhoneticSymbol(String wordPhoneticSymbol) {
        this.wordPhoneticSymbol = wordPhoneticSymbol == null ? null : wordPhoneticSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_detail.word_en
     *
     * @return the value of word_detail.word_en
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public String getWordEn() {
        return wordEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_detail.word_en
     *
     * @param wordEn the value for word_detail.word_en
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void setWordEn(String wordEn) {
        this.wordEn = wordEn == null ? null : wordEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_detail.e_status
     *
     * @return the value of word_detail.e_status
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public Integer geteStatus() {
        return eStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_detail.e_status
     *
     * @param eStatus the value for word_detail.e_status
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void seteStatus(Integer eStatus) {
        this.eStatus = eStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_detail.chapter_id
     *
     * @return the value of word_detail.chapter_id
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public Long getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_detail.chapter_id
     *
     * @param chapterId the value for word_detail.chapter_id
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void setChapterId(Long chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_detail.create_time
     *
     * @return the value of word_detail.create_time
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_detail.create_time
     *
     * @param createTime the value for word_detail.create_time
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column word_detail.update_time
     *
     * @return the value of word_detail.update_time
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column word_detail.update_time
     *
     * @param updateTime the value for word_detail.update_time
     *
     * @mbg.generated Wed May 15 10:50:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}